# Generated by Django 5.1 on 2024-08-29 21:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_provider_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 0, 42, 47, 481709)),
        ),
        migrations.AddField(
            model_name='appointments',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.provider'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('past', 'past')], default='pending', max_length=20),
        ),
    ]
