# Generated by Django 5.1 on 2024-08-29 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointments_client_appointments_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 0, 49, 22, 294983)),
        ),
    ]
