# Generated by Django 5.1 on 2024-08-30 13:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_appointments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 16, 16, 46, 987418)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.provider'),
        ),
    ]
