# Generated by Django 5.1 on 2024-09-01 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_appointments_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth0_id',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 0, 5, 58, 276143)),
        ),
    ]
