# Generated by Django 5.1 on 2024-09-06 16:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customuser_type_remove_provider_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='customuser_ptr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 19, 18, 58, 141729)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.provider'),
        ),
    ]
