# Generated by Django 5.1 on 2024-09-06 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_provider_customuser_ptr_customuser_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 19, 20, 21, 145140)),
        ),
    ]
