# Generated by Django 5.1 on 2024-09-06 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_appointments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 16, 27, 48, 47398, tzinfo=datetime.timezone.utc)),
        ),
    ]
