# Generated by Django 5.1 on 2024-09-12 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_appointments_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_link',
            field=models.CharField(default='https://justpaid-findr-appointment-link.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 22, 50, 35, 368298, tzinfo=datetime.timezone.utc)),
        ),
    ]
