# Generated by Django 5.1 on 2024-09-12 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_appointments_appointment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 22, 51, 59, 635126, tzinfo=datetime.timezone.utc)),
        ),
    ]
