# Generated by Django 5.1 on 2024-09-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_appointments_end_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='start_date_time',
        ),
    ]
